spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: Shubham
    password: Shubham
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/product
    user: Shubham
    password: Shubham
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "init"

server:
  port: 8050
